### ISSUE TITLE
The downloaded files do not have the correct extensions

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/rules_jvm_external#684]
`rules_jvm_external` doesn't append the proper file extensions to the downloaded files which prevents direct consumption. This can be worked around by making a copy that has the correct file extension before passing them to `java_import` and `aar_import`.

Example: `java_import` asserts that the provided inputs for both `jars` and `srcjar` have `.java` as it's file extension. `aar_import` mirrors this behavior by asserting that the provided input has `.aar` as it's file extension.

```python
java_import(
    name = "example_java_import",
	# Produces an error in Bazel
    jars = ["@org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm_1_6_1//file"],
	# Produces an error in Bazel
    srcjar = "@org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm_jar_sources_1_6_1//file:file",
)

aar_import(
    name = "example_aar_import",
	# Produces an error in Bazel
    aar = "@androidx_room_room_runtime_2_4_2//file",
	# Produces an error in Bazel
    srcjar = "@androidx_room_room_runtime_aar_sources_2_4_2//file",
)
```

**Comment by AlexBurdu** [comment]
I'm not sure whether it's the same issue or a different one, but `maven_install` behaves in a similar way when trying to fetch jetpack compose artifacts, which with `1.5.0-beta01` are jars instead of aars (https://mvnrepository.com/artifact/androidx.compose.runtime/runtime/1.5.0-beta01)

```
load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "androidx.compose.runtime:runtime:1.5.0-beta01",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
```

```
java_library(
    name = "compose-runtime",
    exports = ["@maven//:androidx_compose_runtime_runtime"],
)
```

```
https://maven.google.com/androidx/compose/runtime/runtime/1.5.0-beta01/runtime-1.5.0-beta01.aar: not found: https://maven.google.com/androidx/compose/runtime/runtime/1.5.0-beta01/runtime-1.5.0-beta01.aar
```

**Comment by artem-zinnatullin** [comment]
A bit more debugging on an example artifact [foundation-layout:1.5.0-beta01](https://maven.google.com/web/index.html?q=foundation-layout#androidx.compose.foundation:foundation-layout:1.5.0-beta01)

Previous version of it [foundation-layout:1.5.0-alpha04](https://maven.google.com/web/index.html?q=foundation-layout#androidx.compose.foundation:foundation-layout:1.5.0-alpha04) had `.aar` published directly.

New version [foundation-layout:1.5.0-beta01](https://maven.google.com/web/index.html?q=foundation-layout#androidx.compose.foundation:foundation-layout:1.5.0-beta01) has no `.aar`, instead it has `.jar` that only contains Kotlin Multiplatform META-INF.

However for new version there is now `-android` artifact [foundation-layout-android:1.5.0-beta01](https://maven.google.com/web/index.html?q=foundation-layout#androidx.compose.foundation:foundation-layout-android:1.5.0-beta01) which has correct `.aar`.

`.pom` files of androidx dependencies that depend on `foundation-layout:1.5.0-beta01` like [androidx.compose.animation:animation:1.5.0-beta01](https://maven.google.com/web/index.html?q=animation#androidx.compose.animation:animation:1.5.0-beta01) **don't** point to `-android` artifact correctly

```xml
<dependency>
    <groupId>androidx.compose.foundation</groupId>
    <artifactId>foundation-layout</artifactId>
    <version>1.5.0-beta01</version>
    <scope>runtime</scope>
    <type>aar</type>
</dependency>
```

So just relying on `.pom` files will get us nowhere...

---

However, there is additional Gradle Module Metadata file published for each artifact which correctly points to `-android` artifact.

1) Download https://dl.google.com/android/maven2/androidx/compose/foundation/foundation-layout/1.5.0-beta01/foundation-layout-1.5.0-beta01.module

2) Note that it has bunch of `-published` entries which point to `foundation-layout-android` (`-android`) `.module` file

```json
{
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.5.0-beta01/foundation-layout-android-1.5.0-beta01.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.5.0-beta01"
      }
},
```

3) Download https://dl.google.com/android/maven2/androidx/compose/foundation/foundation-layout-android/1.5.0-beta01/foundation-layout-android-1.5.0-beta01.module

4) This file now points to correct `-android.aar`

```json
"files": [
        {
          "name": "foundation-layout-release.aar",
          "url": "foundation-layout-android-1.5.0-beta01.aar",
          "size": 535787,
          "sha512": "06b2aaa6edd18647d6d0fae97ac6fa5e38f135a11183bcdabe4358f61f0de57472e8fff6c078cba5082da1b50f3447f36ce339dba8c054b2f89a7a25d5684921",
          "sha256": "4984eb1b708b9060fb6e70455cf245f7b9604909fca7895c15ebfd8bfd678309",
          "sha1": "e4176d6f734a92095e7f2d59a668af6571cbc6c3",
          "md5": "70bceeb3ccccd0d5557e369548f7d786"
        }
      ]
```

---

So it seems like `rules_jvm_external` needs to add support for `.module` files to resolve Kotlin Multiplatform artifacts correctly :/

**Comment by Bencodes** [comment]
Closing this issue since the original problem was solved already. Any further compose multiplatform discussion will continue in https://github.com/bazelbuild/rules_jvm_external/issues/909

**Comment by geaden** [comment]
> Closing this issue since the original problem was solved already. Any further compose multiplatform discussion will continue in #909

How was the original issue solved? I still get the same issue https://github.com/bazelbuild/rules_jvm_external/issues/684#issuecomment-1566524143 when upgrading from compose 1.4.3 to 1.5.4
